# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/akb/Desktop/staj-II/_space.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1087, 566)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1081, 41))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.btnShowYoutube = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowYoutube.setGeometry(QtCore.QRect(110, 100, 141, 23))
        self.btnShowYoutube.setObjectName("btnShowYoutube")
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(840, 10, 91, 23))
        self.btnLoad.setObjectName("btnLoad")
        self.btnShowNba = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowNba.setGeometry(QtCore.QRect(470, 100, 141, 23))
        self.btnShowNba.setObjectName("btnShowNba")
        self.btnShowOkul = QtWidgets.QPushButton(self.centralwidget)
        self.btnShowOkul.setGeometry(QtCore.QRect(830, 100, 141, 23))
        self.btnShowOkul.setObjectName("btnShowOkul")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 40, 1081, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 20, 351, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cbYoutube = QtWidgets.QComboBox(self.layoutWidget1)
        self.cbYoutube.setIconSize(QtCore.QSize(18, 18))
        self.cbYoutube.setObjectName("cbYoutube")
        self.horizontalLayout.addWidget(self.cbYoutube)
        self.horizontalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 20, 351, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.cbNba = QtWidgets.QComboBox(self.layoutWidget_3)
        self.cbNba.setIconSize(QtCore.QSize(18, 18))
        self.cbNba.setObjectName("cbNba")
        self.horizontalLayout_6.addWidget(self.cbNba)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 20, 351, 22))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.cbOkul = QtWidgets.QComboBox(self.layoutWidget_4)
        self.cbOkul.setIconSize(QtCore.QSize(18, 18))
        self.cbOkul.setObjectName("cbOkul")
        self.horizontalLayout_7.addWidget(self.cbOkul)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 140, 1071, 381))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblYoutube = QtWidgets.QLabel(self.layoutWidget2)
        self.lblYoutube.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblYoutube.setObjectName("lblYoutube")
        self.verticalLayout.addWidget(self.lblYoutube)
        self.lblNba = QtWidgets.QLabel(self.layoutWidget2)
        self.lblNba.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblNba.setObjectName("lblNba")
        self.verticalLayout.addWidget(self.lblNba)
        self.lblOkul = QtWidgets.QLabel(self.layoutWidget2)
        self.lblOkul.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblOkul.setObjectName("lblOkul")
        self.verticalLayout.addWidget(self.lblOkul)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1087, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQt5 ile Veri Analizi"))
        MainWindow.setWindowIcon(QIcon('favicon.ico'))
        self.label.setText(_translate("MainWindow", "PYQT5 İLE VERİ ANALİZİ VE GÖRSELLEŞTİRME"))
        self.btnShowYoutube.setText(_translate("MainWindow", "Görüntüle"))
        self.btnLoad.setText(_translate("MainWindow", "Load Data Items"))
        self.btnShowNba.setText(_translate("MainWindow", "Görüntüle"))
        self.btnShowOkul.setText(_translate("MainWindow", "Görüntüle"))
        self.groupBox.setTitle(_translate("MainWindow", "YouTube"))
        self.label_2.setText(_translate("MainWindow", "ANALİZ SONUÇ SEÇİMİ : "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Nba"))
        self.label_5.setText(_translate("MainWindow", "ANALİZ SONUÇ SEÇİMİ : "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Okul anket ve Fifa"))
        self.label_6.setText(_translate("MainWindow", "ANALİZ SONUÇ SEÇİMİ : "))
        self.lblYoutube.setText(_translate("MainWindow", "Youtube:"))
        self.lblNba.setText(_translate("MainWindow", "Nba:"))
        self.lblOkul.setText(_translate("MainWindow", "Okul & Fifa:"))
